monitor=,preferred,auto,auto
source= hyprland/startup.conf
source= hyprland/theme.conf
source = hyprland/gestures.conf
source = hyprland/keybinds.conf
source = hyprland/input.conf
source = hyprland/rules.conf
