# windows
$c_outline_inactive = rgba(2F1E41FF)
$c_outline_active = rgba(9c2fe0FF)
$c_shadow = rgba(1a1a1a1a)
$c_background = rgba(333333FF)
# fonts
$font_family = JetBrainsMono Nerd Font
$font_color = rgba(FFFFFFFF) 
