$mainMod = SUPER
$terminal = kitty || foot || alacritty || xterm || gnome-terminal || tilix || konsole
$fileManager = dolphin || nautilus || thunar || pcmanfm || nemo || mariner
$browser = librewolf || firefox || msedge || chrome || chromium || brave || vivaldi || qutebrowser
$menu = fuzzel
