exec-once = awww-daemon & xdg-desktop-portal-hyprland & hypridle
# Make sure everything in scripts is executable
exec-once = chmod +x ~/.config/hypr/scripts/*
# Do this on reload to ensure files exist
exec = matugen image $(awww query | awk -F 'image: ' '{print $2}') --prefer darkness -c ~/.config/hypr/matugen/matugen.conf
# Auto reload
exec = pkill waybar; waybar -c ~/.config/hypr/waybar/config/main.json -s ~/.config/hypr/waybar/style.css
exec = pkill mako; mako -c ~/.config/hypr/mako/config

exec-once = systemctl --user start hyprpolkitagent
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,2<S-D-F23>4
