#!/bin/bash
# Dead simple nmcli gui using fuzzel
connect() {
  nmcli device wifi rescan
  CHOICE=$(
    nmcli -t -f SSID,SIGNAL,SECURITY device wifi list |
      awk -F: '
        $1!="" {
            if(!seen[$1] || seen[$1]<$2){
                seen[$1]=$2
                if($2 > 90){icon="󰤨"} 
                else if($2>=70){icon="󰤥"} 
                else if($2>=50){icon="󰤢"} 
                else if($2>=30){icon="󰤟"} 
                else {icon="󰤯"}
                ssid[$1]=icon "\t" $1 " " $3
            }
        }
        END{
            for(i in ssid) print ssid[i]
        }' |
      fuzzel -a top-right -d --placeholder "WiFi Name"
  )
}
connect
if [ -n "$CHOICE" ]; then
  SSID=$(echo "$CHOICE" | awk -F '\ ' '{print $2}' | sed 's/[\t]//g')
  echo $SSID
  SECURITY=$(echo "$CHOICE" | awk -F ' ' '{print $3}')
  echo $SECURITY
  PASSWORD=""
  if [[ "$SECURITY" != "" ]]; then
    echo "Network requires a password, prompting"
    PASSWORD=$(fuzzel -a top-right --password --dmenu --prompt-only="Password for $SSID : ")
    echo "Connecting"
  fi
  STATUS=$(nmcli device wifi connect "$SSID" password "$PASSWORD" 2>&1)
  if [ $? -eq 0 ]; then
    notify-send "󱚽 Network" "Connected to $SSID" -i network-wireless
  else
    notify-send "󱚼 Network" "Failed to connect to $SSID\n$STATUS" -i network-wireless
  fi
fi
